// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSM7PuxpzqDQwZ9QXnPqQUz81OBXNWLM',
    appId: '1:509505118688:android:498828b383757166450b85',
    messagingSenderId: '509505118688',
    projectId: 'career-d3ecc',
    storageBucket: 'career-d3ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTsEruJuuYdDkaJzNuyS7ddixkYdpMp-U',
    appId: '1:509505118688:ios:cdf58493ef8c49fe450b85',
    messagingSenderId: '509505118688',
    projectId: 'career-d3ecc',
    storageBucket: 'career-d3ecc.firebasestorage.app',
    iosBundleId: 'com.example.onlineCourceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iD3j9Y9MClK-bmVkWnOziWYtErl0pjs',
    appId: '1:509505118688:web:78de08abdd5b26db450b85',
    messagingSenderId: '509505118688',
    projectId: 'career-d3ecc',
    authDomain: 'career-d3ecc.firebaseapp.com',
    storageBucket: 'career-d3ecc.firebasestorage.app',
    measurementId: 'G-DJB4LKGT6X',
  );

}